### PR TITLE
fix: remove hardcoded docker occurences.

### LINKED ISSUE #22: Exit handler has hardcoded container engine
In the exit handler there is a hardcoded docker command. Its basically my own bug, since I introduced the engine parameter to make it possible to use srtool with podman.

I'll write a short fix.

### PR DESCRIPTION
**Pull request by trusch**
This PR removes two hardcoded occurences of the docker container engine. Since a few weeks, users can choose to use podman instead of docker, but in some places "docker" was still not made dynamic.

fixes #22

### CODE REVIEW

**Comment by chevdor** [comment]
This is a very welcome fix. Thank you.

I also think it would be good in general to switch the default to Podman but I want to make sure we do not suprise the users who may not have a Podman install ready to be used. Ideally, the doc should be reworked to mention something more neutral than Docker and use the word "containers" instead.

## Quick option
I am thinking that we could drop a warning if the engine is set to `docker` and mention that the default will be switched to `podman` in the next release(s) so users are invited to use or at least test the `podman` engine already.

## Smarter option
As alternative, we could be smart about it and check whether podman and docker are installed and use as engine:
- only podman detected => podman
- only docker detected => docker + warning
- both => whatever the user select but switch  the default to `podman` abd warn the user if they picked `docker`

In term of detection (I ran into this recently), we need to make sure we don't stop at just finding the "command".
I, for instance, use an `alias docker=podman`, since I still end up typiong `docker` by reflex from time to time.

Using `--version` whill give away what the engine really is:
```
docker --version   
podman version 4.5.0
```

The above could be done in this PR or in another one. Your pick :)

**Comment by trusch** [comment]
@chevdor Sorry that it took a while, but I had stuff to do :man_shrugging: Hope you are happy with the result!

**Comment by chevdor** [comment]
No stress and thanks for the work!
I am not sure I can check it today but I will have a look asap.

**Review by chevdor — APPROVED** [review]
I included a few fixes directly

**Pull request merged**
